CREATE TABLE IF NOT EXISTS curso (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(200) NOT NULL,
  fecha_inicio DATE,
  descripcion TEXT,
  creado_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alumno (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  matricula VARCHAR(50) NOT NULL UNIQUE,
  nombre VARCHAR(200) NOT NULL,
  apellido VARCHAR(200) NOT NULL,
  correo VARCHAR(150),
  creado_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
